site_name: irgsctool
site_url: https://sshah1502.github.io/irgsc/
repo_url: https://github.com/sshah1502/irgsc/
edit_uri: tree/main/documentation/docs
site_author: Sarang Shah
use_directory_urls: false
markdown_extensions:
    - pymdownx.snippets:
theme: 
  name: readthedocs
  logo: img/TMTLOGO.PNG
  nav_style: dark
  features:
    - content.action.edit
    - navigation.footer
  icon:
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  - pymdownx.highlight:
      pygments_lang_class: true
markdown_extensions:
  - pymdownx.highlight:
      auto_title: true

plugins:
  - git-committers:
      repository: sshah1502/irgsc/
      branch: main
  - git-authors:
  - optimize
  - offline


plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_source: true
            show_category_heading: false
            show_heading: false
            docstring_section_style: spacy
            show_bases: false
            show_source: false
            merge_init_into_class: true
            fontcolor: black
      watch:
        - docs
  - glightbox
  - search

nav:
  - Home : index.md
  - About : about.md
  - API: apireference.md
  - Tutorials: tutorials.md
  - Acknowledgements: acknowledgements.md
  - License: license.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex: # mathjax
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      toc_depth: 4

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true


markdown_extensions:
  - attr_list
  - md_in_html

markdown_extensions:
  - toc:
        permalink: link
  - pymdownx.arithmatex:
      generic: true
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
